# Generated by Django 4.2 on 2024-10-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_volunteerwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_pics/'),
        ),
    ]
