# Generated by Django 4.2 on 2024-10-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerwork',
            name='image',
        ),
        migrations.AddField(
            model_name='volunteerwork',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
