# Generated by Django 4.2 on 2024-11-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_volunteerwork_image_volunteerwork_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
